# Generated by Django 3.1.2 on 2020-11-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20201109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
