# Generated by Django 3.1.2 on 2020-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20201110_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Cotizacion', 'Cotizacion'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
